# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: csMSP

        # ID to load the MSP definition as
        ID: csMSP

        MSPDir: ../organizations/peerOrganizations/cs.group/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('csMSP.admin', 'csMSP.peer', 'csMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('csMSP.admin', 'csMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('csMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org3MSP.peer')"
